# Generated by Django 4.0.1 on 2022-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_mgt', '0002_post_city_post_state_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
