# Generated by Django 4.0.1 on 2022-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_mgt', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='booked',
            field=models.CharField(max_length=200, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
